import Image from "next/image";

export default function Header() {
  return (
    <header
      className="
        flex
        flex-col
        gap-5
        px-4
        pt-6
        sm:px-6
        lg:flex-row
        lg:items-center
        lg:justify-between
        lg:px-0
        lg:pt-8
      "
    >
      {/* ================= Search Bar ================= */}
      <div
        className="
          flex
          h-[50px]
          w-full
          items-center
          rounded-full
          border
          border-[#E8E8E8]
          bg-white
          px-5
          lg:max-w-[720px]
        "
      >
        <Image
          src="/icons/navbar/search.png"
          alt="Search"
          width={22}
          height={22}
        />

        <input
          type="text"
          placeholder="Search book title or author..."
          className="
            ml-4
            w-full
            bg-transparent
            text-[14px]
            text-[#3A3A3A]
            placeholder:text-[#7C7C7C]
            outline-none
          "
        />
      </div>

      {/* ================= Right Side ================= */}
      <div
        className="
          flex
          items-center
          justify-end
          gap-3
          sm:gap-5
        "
      >
        <button
          className="
            flex
            h-10
            w-10
            items-center
            justify-center
            rounded-full
            bg-white
            transition
            duration-200
            hover:scale-110
          "
        >
          <Image
            src="/icons/navbar/heart.png"
            alt="Wishlist"
            width={18}
            height={18}
          />
        </button>

        <button
          className="
            flex
            h-10
            w-10
            items-center
            justify-center
            rounded-full
            bg-white
            transition
            duration-200
            hover:scale-110
          "
        >
          <Image
            src="/icons/navbar/cart.png"
            alt="Cart"
            width={20}
            height={20}
          />
        </button>

        <button
          className="
            flex
            h-[40px]
            min-w-[96px]
            items-center
            justify-center
            rounded-full
            border
            border-[#B6B6B6]
            bg-white
            px-6
            text-[14px]
            text-[#3A3A3A]
            transition
            hover:bg-gray-50
          "
        >
          Login
        </button>
      </div>
    </header>
  );
}